name = "league-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
NODE_ENV = "production"
CLIENT_URL = "http://localhost:5173"

[triggers]
crons = [ "* * * * *" ]
